language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=1da8f6a0218514df47ede2e3be786d4dbe6c6af3f3c51dde9c8556f81dae8c38
    - NODE_ENV=ci

node_js:
  - "node"
  
services:
  - redis-server

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master
    - staging

install:
  - npm install --only=productiom

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - docker build -t Hild-Franck/be-project-router